import {
  Check,
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  OneToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from "typeorm";
import { User } from "../users/user.entity.js";

/** Whether a driver is currently with the fleet. */
export enum DriverStatus {
  active = "active",
  inactive = "inactive",
}

/**
 * A driver renting a car from the fleet. Maps to the `drivers` table.
 *
 * Created when an admin approves an application (D26). Payments are matched to drivers
 * later (spec M4), which is why email and phone must each belong to only one driver.
 * Kept lean on purpose: billing and aliases are added in later steps.
 */
@Entity("drivers")
@Check("drivers_email_lowercase", `"email" = lower("email")`)
@Check("drivers_phone_e164_us", `"phone" ~ '^\\+1[0-9]{10}$'`)
export class Driver {
  /** Generated by the database (gen_random_uuid()). */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column({ name: "first_name", type: "varchar", length: 100 })
  firstName: string;

  @Column({ name: "last_name", type: "varchar", length: 100 })
  lastName: string;

  /** Stored lower-case (enforced by the CHECK above). Unique across drivers. */
  @Column({ type: "varchar", length: 254, unique: true })
  email: string;

  /**
   * US number in E.164 format, e.g. `+13125550123`: `+1` followed by 10 digits.
   * One stored format means a lookup by phone can never miss because of formatting
   * (`(312) 555-0123` vs `3125550123`). The CHECK above makes the database reject
   * anything else; the code converts the application's 10 digits before saving.
   */
  @Column({ type: "varchar", length: 12, unique: true })
  phone: string;

  /** New drivers start `active`. */
  @Column({
    type: "enum",
    enum: DriverStatus,
    enumName: "driver_status",
    default: DriverStatus.active,
  })
  status: DriverStatus;

  /**
   * The driver's login (a `users` row with role `driver`), created on approval. Null for
   * drivers approved before driver logins existed.
   */
  @Column({ name: "user_id", type: "uuid", nullable: true })
  userId: string | null;

  /** Foreign key to `users`. `OneToOne` also makes `user_id` unique: one login per driver. */
  @OneToOne(() => User, { nullable: true })
  @JoinColumn({ name: "user_id" })
  user?: User | null;

  @CreateDateColumn({ name: "created_at", type: "timestamptz" })
  createdAt: Date;

  @UpdateDateColumn({ name: "updated_at", type: "timestamptz" })
  updatedAt: Date;
}
