import {
  Check,
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from "typeorm";
import { Driver } from "../drivers/driver.entity.js";
import { User } from "../users/user.entity.js";

/** Where an application is in the admin's review. */
export enum ApplicationStatus {
  pending = "pending",
  approved = "approved",
  rejected = "rejected",
  on_hold = "on_hold",
}

/**
 * A driver application from the gonzocar.com form (D26). Maps to the `applications` table.
 *
 * The form sends every value as text and may add fields over time, so the full submission is
 * kept in `payload` and only the fields the admin screens need are copied into typed columns.
 * Values are stored as sent; they are cleaned up only when an approval creates the Driver.
 */
@Entity("applications")
@Check("applications_email_lowercase", `"email" = lower("email")`)
@Check(
  "applications_approved_has_driver",
  `("status" = 'approved') = ("driver_id" IS NOT NULL)`,
)
export class Application {
  /** Generated by the database. Returned to the website as `application_id`. */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  /**
   * Unique id the website generates for each submission. The unique index makes intake
   * idempotent: if the same submission arrives twice, the second insert is rejected by the
   * database and the existing application is returned instead of creating a duplicate.
   */
  @Column({ name: "request_id", type: "varchar", length: 100, unique: true })
  requestId: string;

  @Column({
    type: "enum",
    enum: ApplicationStatus,
    enumName: "application_status",
    default: ApplicationStatus.pending,
  })
  status: ApplicationStatus;

  @Column({ name: "first_name", type: "varchar", length: 100 })
  firstName: string;

  @Column({ name: "last_name", type: "varchar", length: 100 })
  lastName: string;

  /** Lower-cased on intake, so it can be compared with driver emails. Not unique: a person may apply twice. */
  @Column({ type: "varchar", length: 254 })
  email: string;

  /** Phone exactly as sent (the form sends 10 digits). Converted to `+1…` only on approval. */
  @Column({ type: "varchar", length: 30 })
  phone: string;

  @Column({ type: "varchar", length: 100, nullable: true })
  city: string | null;

  @Column({ type: "varchar", length: 10, nullable: true })
  zip: string | null;

  /** When the applicant pressed submit, according to their browser. `createdAt` is when we received it. */
  @Column({ name: "submitted_at", type: "timestamptz", nullable: true })
  submittedAt: Date | null;

  /** Paths of the uploaded files in the client's Supabase `driver-documents` bucket (B17). */
  @Column({
    name: "license_storage_path",
    type: "varchar",
    length: 500,
    nullable: true,
  })
  licenseStoragePath: string | null;

  @Column({
    name: "rating_storage_path",
    type: "varchar",
    length: 500,
    nullable: true,
  })
  ratingStoragePath: string | null;

  @Column({
    name: "earnings_storage_path",
    type: "varchar",
    length: 500,
    nullable: true,
  })
  earningsStoragePath: string | null;

  /**
   * The whole submission as JSON, minus `turnstile_token` (a one-time bot-check token, useless
   * once received). `jsonb` is stored parsed, so Postgres can query inside it if ever needed.
   */
  @Column({ type: "jsonb" })
  payload: Record<string, unknown>;

  /** The admin who last approved, rejected or put it on hold. Null while pending. */
  @Column({ name: "reviewed_by_id", type: "uuid", nullable: true })
  reviewedById: string | null;

  /** Foreign key to `users`: the database guarantees `reviewed_by_id` points at a real user. */
  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: "reviewed_by_id" })
  reviewedBy?: User | null;

  @Column({ name: "reviewed_at", type: "timestamptz", nullable: true })
  reviewedAt: Date | null;

  /**
   * The driver created by approving this application. Set only when approved (enforced by the
   * `applications_approved_has_driver` CHECK above).
   */
  @Column({ name: "driver_id", type: "uuid", nullable: true })
  driverId: string | null;

  /**
   * Foreign key to `drivers`. `OneToOne` also makes `driver_id` unique, so two applications can
   * never point at the same driver.
   */
  @OneToOne(() => Driver, { nullable: true })
  @JoinColumn({ name: "driver_id" })
  driver?: Driver | null;

  /** When our API received the submission. */
  @CreateDateColumn({ name: "created_at", type: "timestamptz" })
  createdAt: Date;

  @UpdateDateColumn({ name: "updated_at", type: "timestamptz" })
  updatedAt: Date;
}
