import {
  Check,
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from "typeorm";

/**
 * What kind of account a user is.
 * Only `admin` can log in today; `driver` is reserved for a future driver portal.
 */
export enum Role {
  admin = "admin",
  driver = "driver",
}

/**
 * A person who can log in to the system. Maps to the `users` table;
 * one instance of this class is one row.
 *
 * The table itself is created and changed only by migrations
 * (src/database/migrations), never by editing this class alone.
 */
@Entity("users")
@Check("users_email_lowercase", `"email" = lower("email")`)
export class User {
  /** Generated by the database (gen_random_uuid()); never set by hand. */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  /**
   * Login email, stored lower-case. `unique: true` creates a unique index, so two
   * accounts can never share an email even if two requests arrive at the same instant.
   * The CHECK above makes the database itself reject upper-case emails.
   *
   * Every column needs an explicit `type`: the migration tool runs without TypeScript's
   * emitted type metadata, so TypeORM cannot guess that `string` means varchar.
   */
  @Column({ type: "varchar", length: 254, unique: true })
  email: string;

  /**
   * bcrypt hash of the password (never the password itself).
   * `select: false` keeps it out of normal queries; login asks for it explicitly.
   */
  @Column({
    name: "password_hash",
    type: "varchar",
    length: 255,
    select: false,
  })
  passwordHash: string;

  /**
   * Account type. There is deliberately no default, so a role must always be
   * chosen explicitly and can never be granted by accident.
   */
  @Column({ type: "enum", enum: Role, enumName: "user_role" })
  role: Role;

  /** Inactive accounts cannot log in. */
  @Column({ type: "boolean", default: true })
  active: boolean;

  /** Filled in automatically on insert. `timestamptz` stores an exact moment (UTC). */
  @CreateDateColumn({ name: "created_at", type: "timestamptz" })
  createdAt: Date;

  /** Refreshed automatically whenever the row is saved through TypeORM. */
  @UpdateDateColumn({ name: "updated_at", type: "timestamptz" })
  updatedAt: Date;
}
